### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hamzaaumerr** [HarryDulaney/intro-to-java-programming#15]
https://github.com/HarryDulaney/intro-to-java-programming/blob/a1661539ea1b0f0f56684de309e75d0a463bfdd9/src/ch_02/Exercise02_13.java#L40

Replace 100 with monthDeposit.

**Comment by HarryDulaney** [comment]
Thank you! @hamzaaumerr I am updating it now.

**Comment by HarryDulaney** [comment]
https://github.com/HarryDulaney/intro-to-java-programming/blob/15792ec8d22c9d9b69025003e9bb5cec207374c8/src/ch_02/Exercise02_13.java
