### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hamzaaumerr** [HarryDulaney/intro-to-java-programming#19]
https://github.com/HarryDulaney/intro-to-java-programming/blob/be321adbf4d06e73ff5dfb72ccb96c1e75b32049/src/ch_03/Exercise03_26.java#L29

**Replace 10 with user input in lines 29-31.**

**Comment by HarryDulaney** [comment]
Thank you @hamzaaumerr! The fix for this has been Merged.

**Comment by HarryDulaney** [comment]
See commit:  Fix console out print on Exercise03_26.java #21
