### ISSUE TITLE
18.20 and 18.21 exercise missing

### ISSUE THREAD

**Issue by tannorg** [HarryDulaney/intro-to-java-programming#2]
Did u complete these exercises in that chapter 18?

**Comment by tannorg** [comment]
Maze problems in the book

**Comment by HarryDulaney** [comment]
Still working on Chapter 18, I'll take a look at 18.20 and 18.21 and post a solution shortly.

**Comment by HarryDulaney** [comment]
[Added Ch 18 Ex. 20](https://github.com/HarryDulaney/intro-to-java-programming/blob/master/src/ch_18/Exercise18_20.java)
[Added Ch 18 Ex. 21](https://github.com/HarryDulaney/intro-to-java-programming/blob/master/src/ch_18/Exercise18_21.java)
