### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hamzaaumerr** [HarryDulaney/intro-to-java-programming#24]
* Three constants named SLOW, MEDIUM, and FAST with the values 1, 2, and 3 to denote the fan speed.
From line 48 to 50
In question, they say declare three constants but you write protected static instead of final keyword. This is a mistake or you write this due to any specific reason?

https://github.com/HarryDulaney/intro-to-java-programming/blob/4af778fcdaf7ac523b2cb7f0112354ce82e14f75/src/ch_09/exercise09_08/Fan.java#L48

**Comment by HarryDulaney** [comment]
That's a good point, I updated the speed variables to be constants. Thank you for finding this issue.
