### ISSUE TITLE
Change in the existing solulion of Exercise18_02 of ch_18

### ISSUE THREAD

**Issue by Sahilkumar19** [HarryDulaney/intro-to-java-programming#54]
given solution is completely right ...but here is the more optimized solulion without using any loop after solving the recurrence relation of the fibonacci number we will get a direct formula to get the nth fibonacci term. On further solving the formula we will get the time complexity of this program as golden ration raised to the power n which is equal to O(1.6180)^n.

**Comment by HarryDulaney** [comment]
Exercise 18.02 says: 
*18.2 (Fibonacci numbers) Rewrite the fib method in Listing 18.2 using iterations.

The purpose of this exercise is actually to use a traditional iterative or looping approach to solving fibinanci numbers. 

closing this as it is not actually an issue*
